parameters:
  jobName: release
  imageName: windows-2019
  displayName: 'Release Microsoft.PowerShell.ThreadJob to NuGet'

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  displayName: ${{ parameters.displayName }}

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifacts'
    inputs:
      buildType: current
      downloadType: specific
      itemPattern: '**/*.nupkg'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'

  - powershell: |
      Get-ChildItem '$(System.ArtifactsDirectory)/nupkg/Microsoft.PowerShell.ThreadJob.*.nupkg'
    displayName: 'Capture NuGet package'

  - task: NuGetCommand@2
    displayName: 'Push PSThreadJob artifacts to AzArtifactFeed'
    inputs:
      command: push
      packagesToPush: '$(System.ArtifactsDirectory)/nupkg/Microsoft.PowerShell.ThreadJob.*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: AzArtifactFeed

  - task: NuGetCommand@2
    displayName: 'Push PSThreadJob artifacts from AzArtifactFeed to PSGallery feed'
    inputs:
      command: push
      packagesToPush: '$(System.ArtifactsDirectory)/nupkg/Microsoft.PowerShell.ThreadJob.*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: PHPowerShellGalleryFeed
